sudo: required
language: python
python:
  - "3.6"

install:
  - sudo apt-get update -qq
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q -y conda
  - conda info -a
  - conda create -c bioconda -c conda-forge -q -y -n test-environment python=$TRAVIS_PYTHON_VERSION blast=2.7.1 git
  - source activate test-environment
  - python setup.py install
  - staramr db restore -f

script: python setup.py test
