sudo: required
language: python
python:
  - "3.6"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git ncbi-blast+
  - ./setup-db.sh
  - python setup.py install

script: python setup.py test
