sudo: required
language: python
python:
  - "3.5"
  - "3.6"

env:
  matrix:
    - "DATABASE_COMMITS='--resfinder-commit 25ee4cd5bc9a9ff519b2fc7e53384aceb5fa942d --pointfinder-commit 7fdb7f4cddfb06932e1ae0c6d3b23a0f297d7922'"

install:
  - sudo apt-get update -qq
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q -y conda
  - conda info -a
  - conda create -c bioconda -c conda-forge -q -y -n test-environment python=$TRAVIS_PYTHON_VERSION blast=2.7.1 git
  - source activate test-environment
  - python setup.py install
  - staramr db build --dir staramr/databases/data $DATABASE_COMMITS
  - pip install mypy==0.600

script: ./scripts/mypy && python setup.py test
