sudo: required
language: python
python:
  - "3.6"

install:
  - echo $TRAVIS_BUILD_DIR
  - sudo apt-get update -qq
  - sudo apt-get install -qq git ncbi-blast+
  - pip install -r requirements.txt

script: export PYTHONPATH=$PYTHONPATH:$(pwd); ./run-tests.sh
