sudo: required
language: python
python:
  - "3.6"
  - "3.7"

env:
  matrix:
    - "DATABASE_COMMITS='--resfinder-commit e8f1eb2585cd9610c4034a54ce7fc4f93aa95535 --pointfinder-commit 8706a6363bb29e47e0e398c53043b037c24b99a7'"

install:
  - sudo apt-get update -qq
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q -y conda
  - conda info -a
  - conda create -c bioconda -c conda-forge -q -y -n test-environment python=$TRAVIS_PYTHON_VERSION blast=2.7.1 git
  - source activate test-environment
  - python setup.py install
  - staramr db build --dir staramr/databases/data $DATABASE_COMMITS
  - pip install mypy==0.600

script: ./scripts/mypy && python setup.py test
